version: 2

models:
  - name: fat_trips
    description: Yellow and Green taxis are traditionally hailed by signaling to a driver who is on duty and seeking a passenger.
    columns:
      - name: fat_key
        data_type: INTEGER
        description: Fat surrogate key.
        data_tests:
          - not_null
      - name: vendor_key
        data_type: INTEGER
        description: A surrogate code indicating the TPEP provider that provided the record.
        data_tests:
          - not_null
      - name: pickup_datetime
        data_type: TIMESTAMP
        description: The date and time when the meter was engaged.
      - name: dropoff_datetime
        data_type: TIMESTAMP
        description: The date and time when the meter was disengaged.
      - name: passenger_count
        data_type: BIGINT
        description: The number of passengers in the vehicle. This is a driver-entered value.
      - name: trip_distance
        data_type: DOUBLE
        description: The elapsed trip distance in miles reported by the taximeter.
      - name: trip_distance_km
        data_type: DOUBLE
        description: The elapsed trip distance in kilometers reported by the taximeter.
      - name: pu_location_key
        data_type: INTEGER
        description: TLC Taxi Zone in which the taximeter was engaged
        data_tests:
          - not_null
      - name: do_location_key
        data_type: INTEGER
        description: TLC Taxi Zone in which the taximeter was disengaged
        data_tests:
          - not_null
      - name: ratecode_key
        data_type: BIGINT
        description: The surrogate rate code in effect at the end of the trip.
        data_tests:
          - not_null
      - name: payment_key
        data_type: INTEGER
        description: A surrogate code signifying how the passenger paid for the trip.
        data_tests:
          - not_null
      - name: service_key
        data_type: INTEGER
        description: Surrogate for green or yellow taxi service.
        data_tests:
          - not_null
      - name: fare_amount
        data_type: DOUBLE
        description: The time-and-distance fare calculated by the meter.
      - name: extra
        data_type: DOUBLE
        description: Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges.
      - name: mta_tax
        data_type: DOUBLE
        description: $0.50 MTA tax that is automatically triggered based on the metered rate in use.
      - name: improvement_surcharge
        data_type: DOUBLE
        description: $0.30 improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015.
      - name: tip_amount
        data_type: DOUBLE
        description: Tip amount – This field is automatically populated for credit card tips. Cash tips are not included.
      - name: tolls_amount
        data_type: DOUBLE
        description: Total amount of all tolls paid in trip.
      - name: total_amount
        data_type: DOUBLE
        description: The total amount charged to passengers. Does not include cash tips.
      - name: congestion_surcharge
        data_type: DOUBLE
        description: Total amount collected in trip for NYS congestion surcharge.
      - name: fee
        data_type: DOUBLE
        description: $1.25 for pick up only at LaGuardia and John F. Kennedy Airports.
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.
      - name: loded_at
        data_type: TIMESTAMP
        description: Day and time of table load.

  - name: dim_payments
    description: The Payment types.
    columns:
      - name: payment_key
        data_type: VARCHAR
        description: The passenger surrogate key.
      - name: payment_id
        data_type: INTEGER
        description: The passenger type identifier.
        data_tests:
          - unique
      - name: payment_desc
        data_type: VARCHAR
        description: The passenger paid type for the trip.
        data_tests:
          - not_null
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.

  - name: dim_ratecodes
    description: The Rate code types.
    columns:
      - name: ratecode_key
        data_type: VARCHAR
        description: The ratecode surrogate key.
      - name: ratecode_id
        data_type: INTEGER
        description: The final rate code in effect at the end of the trip..
        data_tests:
          - unique
      - name: ratecode_desc
        data_type: VARCHAR
        description: Rate code description.
        data_tests:
          - not_null
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.

  - name: dim_services
    description: The Trip services type.
    columns:
      - name: service_key
        data_type: VARCHAR
        description: The service surrogate key.
      - name: service_id
        data_type: INTEGER
        description: The service identifier.
        data_tests:
          - unique
      - name: service_desc
        data_type: VARCHAR
        description: Service description.
        data_tests:
          - not_null
          - accepted_values:
              values: ['GREEN','YELLOW']
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.

  - name: dim_vendors
    description: The Vendor types.
    columns:
      - name: vendor_key
        data_type: VARCHAR
        description: The vendor surrogate key.
      - name: vendor_id
        data_type: INTEGER
        description: A code indicating the TPEP provider that provided the record.
        data_tests:
          - unique
      - name: vendor_desc
        data_type: VARCHAR
        description: Vendor description.
        data_tests:
          - not_null
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.

  - name: dim_zones
    description: The zone types.
    columns:
      - name: zone_key
        data_type: VARCHAR
        description: The zone surrogate key.
        data_tests:
          - unique
      - name: location_id
        data_type: INTEGER
        data_tests:
          - not_null
      - name: borough
        data_type: VARCHAR
      - name: zone
        data_type: VARCHAR
      - name: service_zone
        data_type: VARCHAR
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.

  - name: dim_calendar
    description: The calendar dimension.
    columns:
      - name: date_key
        data_type: VARCHAR
        description: The calendar surrogate key.
        data_tests:
          - unique
      - name: date
        data_type: INTEGER
        data_tests:
          - not_null
      - name: year
        data_type: INTEGER
      - name: quarter
        data_type: INTEGER
      - name: month
        data_type: INTEGER
      - name: month_name
        data_type: VARCHAR
      - name: day
        data_type: INTEGER
      - name: day_of_week
        data_type: INTEGER
      - name: day_of_week_name
        data_type: VARCHAR
      - name: is_weekend
        data_type: BOOLEAN
      - name: is_weekday
        data_type: BOOLEAN
      - name: created_at
        data_type: TIMESTAMP
        description: Day and time of table creation.
