name: nyc-data-pipeline

services:
  dagster:
    image: dagster
    container_name: nyc_dagster
    ports:
      - 4000:4000
    env_file:
      ./docker.env
    volumes:
      - ${PWD}/data:/opt/dagster/app/data
    networks:
      - dagster-net
    restart: on-failure

  minio:
    image: minio/minio:latest
    container_name: nyc_minio
    hostname: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data

  streamlit:
    image: streamlit:latest
    container_name: nyc_streamlit
    environment:
      DUCKDB_PATH: /data
    volumes:
      - ${PWD}/data:/data
    ports:
      - 8501:8501
    depends_on:
      - dagster
    restart: on-failure

networks:
  dagster-net:
    driver: bridge
