name: nyc-data-pipeline

services:
  dagster:
    image: dagster
    container_name: nyc_dagster
    ports:
      - 4000:4000
    env_file:
      ./docker.env
    volumes:
      - ${PWD}/data:/opt/dagster/app/data
    networks:
      - nyc_network
    restart: on-failure

  streamlit:
    image: streamlit:latest
    container_name: nyc_streamlit
    environment:
      DUCKDB_PATH: /data
    volumes:
      - ${PWD}/data:/data
    ports:
      - 8501:8501
    networks:
      - nyc_network
    depends_on:
      - dagster
    restart: on-failure

networks:
  nyc_network:
    driver: bridge
