
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_transformation'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_transformation'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  dbt_transformation:
    staging:
      stg_taxi_trips:
        +materialized: table
        +on_table_exists: drop
        +schema: staging
        +post-hook:
          - "{{ export_to_minio('staging','stg_taxi_trips') }}"
    silver:
      fat_trips:
        +materialized: table
        +on_table_exists: drop
        +schema: silver
        +post-hook:
          - "{{ export_to_minio('silver','fat_trips') }}"
      dim_payments:
        +materialized: table
        +schema: silver
        +on_table_exists: drop
        +post-hook:
          - "{{ export_to_minio('silver','dim_payments') }}"
      dim_ratecodes:
        +materialized: table
        +schema: silver
        +on_table_exists: drop
        +post-hook:
          - "{{ export_to_minio('silver','dim_ratecodes') }}"
      dim_services:
        +materialized: table
        +schema: silver
        +on_table_exists: drop
        +post-hook:
          - "{{ export_to_minio('silver','dim_services') }}"
      dim_zones:
        +materialized: table
        +schema: silver
        +on_table_exists: drop
        +post-hook:
          - "{{ export_to_minio('silver','dim_zones') }}"
      dim_vendors:
        +materialized: table
        +schema: silver
        +on_table_exists: drop
        +post-hook:
          - "{{ export_to_minio('silver','dim_vendors') }}"
      dim_calendar:
        +materialized: table
        +schema: silver
        +on_table_exists: drop
        +post-hook:
          - "{{ export_to_minio('silver','dim_calendar') }}"
